### ISSUE TITLE
How to get results in validation set

### ISSUE THREAD

**Issue by onexmaster** [KaihuaTang/LVIS-for-mmdetection#1]
The lvis datasets validation dataset annotations file is has image name as COCO_val2014_000xx
Do we have to rename them?
Whenever i try to run the validation set as my test set. I get a cuda out of memory error.
I am using your config file as the config file for mmedetector htc model
I did follow all the instructions mentioned and trained the model for 2 epochs.
But i cannot get mask AP and bbox Ap on the validation set.
Any help would be appreciated

**Comment by KaihuaTang** [comment]
The first question, yes, we need to rename the images.

The second, I'm using 8 * P-100 (16G each) GPUs. If your gpu memory is less than 16G,  it may cause cuda out of memory error (depending on what kind of model you choose).

About mask AP and bbox AP,  maybe you forgot to add --validate option?

![image](https://user-images.githubusercontent.com/24402685/80224867-e7213000-867c-11ea-95a7-d5b56ec440f4.png)

**Comment by onexmaster** [comment]
I had only 2 Tesla k80 gpus, that explains the cuda of memory issues.
Thanks for the quick response.
